---
--- Generated by Luanalysis
--- Created by garrett.
--- DateTime: 5/9/23 9:14 PM
---
local status_ok, bufferline = pcall(require, "bufferline")
if not status_ok then
    return
end

vim.opt.termguicolors = true
bufferline.setup()