---
--- Generated by Luanalysis
--- Created by garrettg.
--- DateTime: 2023-05-07 10:10 p.m.
---
local opts = { noremap = true, silent = true }

local term_opts = { silent = true }

-- Shorten function name
local keymap = vim.api.nvim_set_keymap

--Remap space as leader key
keymap("", "<Space>", "<Nop>", opts)
vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- Modes
--   normal_mode = "n",
--   insert_mode = "i",
--   visual_mode = "v",
--   visual_block_mode = "x",
--   term_mode = "t",
--   command_mode = "c",

vim.api.nvim_set_keymap(
        "n",
        "<leader>fb",
        ":Telescope file_browser path=%:p:h select_buffer=true",
        { noremap = true }
)

vim.api.nvim_set_keymap(
        "n",
        "<leader>ff",
        ":Telescope find_files",
        { noremap = true }
)

vim.api.nvim_set_keymap(
        "n",
        "<leader>fr",
        ":Telescope oldfiles",
        { noremap = true }
)

vim.api.nvim_set_keymap(
        "n",
        "<leader><leader>",
        ":Telescope oldfiles",
        { noremap = true }
)